### ISSUE TITLE
error 2

### ISSUE THREAD

**Issue by Zibri** [jeroenmeulenaar/python3-mega#3]
`python3 -m pip install python-mega`
Collecting python-mega
  Using cached https://files.pythonhosted.org/packages/70/9b/3de063ec348456d19ab310b176db8d212528e446da2ae78fc0a3844a78ac/python-mega-0.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-_ckzsvc0/python-mega/setup.py", line 48
        print "You probably want to also tag the version now:"
                                                             ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print(int "You probably want to also tag the version now:")?
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-_ckzsvc0/python-mega/

**Comment by jeroenmeulenaar** [comment]
This respository isn't packed as "python-mega" on pypy.
